name: campushub_mobile
description: Campus Hub — premium university mobile app (Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  dio: ^5.7.0
  socket_io_client: ^2.0.3+1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  timeago: ^3.7.0
  shimmer: ^3.0.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
